// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reactivities.Data;

#nullable disable

namespace Reactivities.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240607175937_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Reactivities.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cffdd9b-a41e-4258-876b-1d89ade3d9b6"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 4, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(8877),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("139726e5-8604-40b6-af16-4ae89b6d96ca"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 5, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(8893),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("b5a00b3a-0127-4c04-b01d-42b2d28b2676"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 7, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(8898),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("b808bb9c-32c1-4b82-bf6f-3b653f4708f7"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 8, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(8919),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("8ac06dbf-a11e-4b26-b456-9dd46f6e7dce"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 9, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(8924),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("f63db6ac-2ddf-456a-8114-582af4ddea1f"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 10, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(8927),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("dca24dab-e37e-425a-9b25-4de54cf8999d"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 11, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(8931),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("c6b053f1-d87a-4f50-a9d8-d3a7a94f5391"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 12, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(9017),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("a431303e-cd01-45ae-858d-28933282a33b"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2025, 1, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(9023),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("e99d2f53-7f03-417f-a2fb-ab11f4ee181b"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2025, 2, 7, 17, 59, 36, 820, DateTimeKind.Utc).AddTicks(9028),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
